// <auto-generated />
using System;
using BlogAPI.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230718102753_Data seed")]
    partial class Dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogAPI.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "I’ve used these features of Git for years across teams and projects. I’m still developing opinions around some workflows (like to squash or not) but the core tooling is powerful and flexible (and scriptable!).\r\n\r\nGoing through Git logs\r\nGit logs are gross to go through out of the box.\r\n\r\ngit log is basic\r\nUsing git log gives you some information. But it’s extremely high-resolution and not usually what you’re looking for.",
                            CreatedDate = new DateTime(2023, 7, 18, 12, 27, 53, 670, DateTimeKind.Local).AddTicks(2751),
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Use Git like a senior engineer",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "When I started working with microservices, I took the common rule of “two services must not share a data source” a bit too literally.\r\n\r\nI saw it stapled everywhere on the internet: “thou shalt not share a DB between two services”, and it definitely made sense. A service must own its data and retain the freedom to change its schema as it pleases, without changing its external-facing API.\r\n\r\nBut there’s an important subtlety here that I didn’t understand until much later. To apply this rule properly, we have to distinguish between sharing a data source and sharing data.",
                            CreatedDate = new DateTime(2023, 7, 18, 12, 27, 53, 670, DateTimeKind.Local).AddTicks(2807),
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sharing Data Between Microservices",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "A friend of mine recently joined a FAANG company as an engineering manager, and found themselves in the position of recruiting for engineering candidates.\r\n\r\nWe caught up.\r\n\r\n“Well,” I laughed when they inquired about the possibility of me joining the team, “I’m not sure I’ll pass the interviews, but of course I’d love to work with you again! I’ll think about it.”\r\n\r\n“That’s the same thing X and Y both said,” they told me, referring to other engineers we had worked with together. “They both said they…\r\n\r\n",
                            CreatedDate = new DateTime(2023, 7, 18, 12, 27, 53, 670, DateTimeKind.Local).AddTicks(2811),
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Why Experienced Programmers Fail Coding Interviews",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BlogAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jacob.benett@gmail.com",
                            FirstName = "Jacob",
                            LastName = "Benett",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Email = "vinay.gupta@gmail.com",
                            FirstName = "Vinay",
                            LastName = "Gupta",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Email = "nicholas.henrikson@gmail.com",
                            FirstName = "Nicholas",
                            LastName = "Henrikson",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("BlogAPI.Entities.Blog", b =>
                {
                    b.HasOne("BlogAPI.Entities.User", null)
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogAPI.Entities.User", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
